# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

### Site metadata ###
#Project Info
site_name: RMTechTransfer Blog
site_description: Random blog to track the randomness and curiosity, across my personal and professional endevours
site_author: Robert Mueller Jr

# Repository
repo_url: https://github.com/okbobm/rmtechtransfer_blog
edit_uri: ""

# Configuration
theme: 
    name: material  

plugins:
  - search:
      separator: "[\\s\\-,:!=\\[\\]()\"/]+|\\.(?!\\d)|&[lg]t;|(?!\\b)(?=[A-Z][a-z])"
  - tags:
      tags_file: tags.md

nav:
  - AboutMe:
    - aboutme/aboutme.md
  - Blog:
    - blog/posts/2023/20230122_FAAGrounded.md
    - blog/posts/2023/20230105_gettingstarted.md 
    - blog/posts/2022/20221217_newblog.md 
   
  - Resume:
    - resume/resume.md
  - Tags:
      tags.md